---
title: "Recruitment Devs"
format: pdf
---


Our general assumption here is that "recruitment deviations" are a log-normally distributed multiplicative process error term. 


In english then, if we assume that there is some average number of recruits in a given time step, whether that is a fixed average or a spawner-recruit relationship, the recruitment deviates estimate the multiplicative deviations from this average

$$rec_t = \bar{rec_t} \times \alpha_t $$

Ignoring then the average recruitment process $\bar{rec_t}$, our goal is to estimate $\alpha_t$

Clearly, we could just let $\alpha_t$ be $\sim Uniform [-\infty,\infty]$ but we know a few things, namely that it has to be positive, and that we probably need some constraint on how much it can vary. 

A simple and common solution to this then is just to estimate

$$log(\alpha_t) \sim N(0,\sigma_r) $$

This is what we do at least in the last version of the code I have access to, ignoring the auto-correlation fun. 

It practice, it turns out that this structure can be a bit harder for a model to estimate due to a fun thing called the devil (or Neil's, depending on where you read it) funnel (https://mc-stan.org/docs/stan-users-guide/reparameterization.html). 

It's much easier for the model to estimate a "non-centered" parameterization of this, where we actually estimate two parameters

The first is we estimate the standard deviations of the deviates. In other words, raw is "how many standard deviations from the mean is this given deviate"

$$raw_t \sim normal(0,1)$$

We then estimate the standard deviation of this process

$$\sigma_r \sim SomeDistribution$$
The actual log recruitment deviates are then calculated as the standard deviation of the lognormal deviates times the "number" of standard deviations from the mean of a given deviate. 

$$log(\alpha_t) = raw_t \times \sigma_r$$

To get back to the deviates on the unit scale, we have to do a log-transformation bias correction, see lots of annoying stats literature (
Punt, André E. “Those Who Fail to Learn from History Are Condemned to Repeat It: A Perspective on Current Stock Assessment Good Practices and the Consequences of Not Following Them.” Fisheries Research 261 (May 1, 2023): 106642. https://doi.org/10.1016/j.fishres.2023.106642.)

$$\alpha_t = e^{log(\alpha_t) - \sigma_r^2/2}$$


```{r}
t <- 25

sigma_r <- 0.2


```

