---
output: 
  bookdown::pdf_document2:
    toc: false
classoption: portrait 
header-includes: 
  - \renewcommand{\figurename}{Supplementary Figure }
  - \renewcommand{\tablename}{Supplementary Table}
  - \makeatletter 
  - \def\fnum@figure{\figurename\thefigure}
  - \makeatother
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, echo=FALSE, results="hide",message=FALSE, warning=FALSE, include=FALSE}
set.seed(42)
library(tidyverse)
library(here)
library(ggplot2)
library(kableExtra)
dat <- read_csv(here("processed-data","flounder_catch_at_length_fall_training.csv"))
dat_test <- read_csv(here("processed-data","flounder_catch_at_length_fall_testing.csv"))
dat_catchonly <- read_csv(here("processed-data","flounder_catch_fall_training.csv"))
dat_test_catchonly <- read_csv(here("processed-data","flounder_catch_fall_testing.csv"))
convergence_checks <- read_csv(file=here("results","convergence_checks.csv"))
ctrl_file <- read_csv(file=here("control_file.csv"))
best_drm_table <- read_csv(file=here("results","best_drm_table.csv"))
```

```{r opts, setup2, include=FALSE}
knitr::opts_chunk$set(
  message=FALSE, echo=FALSE, warning=FALSE
)
#knitr::opts_knit$set(eval.after = "fig.cap")
```


```{r tbl-surveys}

best_drm_table %>% 
kbl(booktabs=TRUE, digits=3) %>%
  kable_styling(font_size = 8, latex_options = c("striped"), full_width=F)
```
